Update training.py
Solved errors when doing np.round(y_pred).astype(int)
AttributeError: 'Tensor' object has no attribute 'rint'
TypeError: loop of ufunc does not support argument 0 of type Tensor which has no callable rint method