Patch 2 (#2)
* Update README.md

* Update training.py

Solved errors when doing np.round(y_pred).astype(int)
AttributeError: 'Tensor' object has no attribute 'rint'
TypeError: loop of ufunc does not support argument 0 of type Tensor which has no callable rint method

* Update protein_embeddings.py

removed tab and replaced with spaces

* Update util_embeddings.py

removed tabs and replaced by spaces